apiVersion: v1
kind: Pod
metadata:
  name: pod-giropops
  labels:
    type: pod
    app: giropops
    run: giropops
    env: development
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
  - name: alpine
    image: alpine:latest
    command: ["/bin/sh"] # Use /bin/sh as the entrypoint
    args: ["-c", "while true; do /bin/sh; done"] # Keep the container running
    stdin: true # Keep stdin open
    tty: true # Allocate a TTY