apiVersion: v1
kind: Pod
metadata:
  name: pod-giropops
  labels:
    type: pod
    app: giropops
    run: giropops
    env: development
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
  - name: alpine
    image: alpine:latest
    args:
    - sleep
    - "1800"