apiVersion: v1
kind: Pod
metadata:
  name: pod-giropops
  labels:
    type: pod
    app: giropops
    run: giropops
    env: development
spec:
  containers:
  - name: ubuntu
    image: ubuntu:22.04
    args:
    - sleep
    - "infinity"
    volumeMounts:
    - name: primeiro-emptydir
      mountPath: /giropops
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  volumes:
  - name: primeiro-emptydir
    emptyDir:
      sizeLimit: "128Mi"